placeholder:
  url: https://jsonplaceholder.typicode.com

logging:
  level:
    com:
      feign:
        parctice:
          feign:
            service:
              Posts: DEBUG
server:  http2:    enabled: true
